CODE_EXTENSION_DESCRIPTIONS = {
    ".py": "Python",
    ".pyi": "Python (типизация)",
    ".pyx": "Cython",
    ".js": "JavaScript",
    ".jsx": "JavaScript (JSX)",
    ".ts": "TypeScript",
    ".tsx": "TypeScript (TSX)",
    ".go": "Go",
    ".java": "Java",
    ".c": "C",
    ".cc": "C++",
    ".cpp": "C++",
    ".h": "C/C++ Header",
    ".hpp": "C++ Header",
    ".rs": "Rust",
    ".rb": "Ruby",
    ".php": "PHP",
    ".cs": "C#",
    ".kt": "Kotlin",
    ".kts": "Kotlin (Script)",
    ".swift": "Swift",
    ".m": "Objective-C",
    ".mm": "Objective-C++",
    ".vb": "Visual Basic",
    ".bas": "BASIC",
    ".sql": "SQL",
    ".pas": "Pascal",
    ".dpr": "Delphi/Pascal",
    ".pp": "Pascal",
    ".r": "R",
    ".pl": "Perl",
    ".pm": "Perl Module",
    ".f": "Fortran",
    ".for": "Fortran",
    ".f90": "Fortran",
    ".f95": "Fortran",
    ".f03": "Fortran",
    ".f08": "Fortran",
    ".sb3": "Scratch",
    ".adb": "Ada",
    ".ads": "Ada (Spec)",
    ".asm": "Assembly",
    ".s": "Assembly",
    ".ino": "Arduino",
    ".htm": "HTML",
    ".html": "HTML",
    ".css": "CSS",
    ".clp": "CLIPS",
    ".clle": "IBM Control Language",
    ".rpgle": "IBM Language Extention",
    ".dspf": "IBM Display File",
    ".bnd": "IBM Bind File",
    ".sqlc": "SQL C",
    ".lisp": "Lisp",
    ".lsp": "Lisp",
    ".lspx": "Lisp (Script)",
    ".lua": "Lua",
}

DOC_EXTENSION_DESCRIPTIONS = {
    ".md": "Markdown",
    ".rst": "reStructuredText",
    ".adoc": "AsciiDoc",
    ".txt": "Text",
}

CONFIG_EXTENSION_DESCRIPTIONS = {
    ".yml": "YAML",
    ".yaml": "YAML",
    ".json": "JSON",
    ".toml": "TOML",
    ".ini": "INI",
    ".cfg": "Config",
    ".conf": "Config",
    ".env": "Environment",
    ".properties": "Properties",
}

CODE_EXTENSIONS = set(CODE_EXTENSION_DESCRIPTIONS)
DOC_EXTENSIONS = set(DOC_EXTENSION_DESCRIPTIONS)
CONFIG_EXTENSIONS = set(CONFIG_EXTENSION_DESCRIPTIONS)
DATA_EXTENSIONS = {".csv", ".tsv", ".parquet", ".avro", ".jsonl"}

K8S_FILENAMES = {
    "deployment.yaml",
    "deployment.yml",
    "service.yaml",
    "service.yml",
    "ingress.yaml",
    "ingress.yml",
    "kustomization.yaml",
    "kustomization.yml",
}

CI_FILENAMES = {".gitlab-ci.yml", "Jenkinsfile", "azure-pipelines.yml"}
CI_PATH_MARKERS = {".github/workflows", ".circleci", ".buildkite"}
CI_FILENAMES_EXTRA = {"bitbucket-pipelines.yml", "buildkite.yml", "pipeline.yml"}

HELM_FILENAMES = {"Chart.yaml", "Chart.yml", "values.yaml", "values.yml"}

DOCKER_FILENAMES = {
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    "compose.yaml",
    "compose.yml",
}

OBSERVABILITY_FILENAMES = {
    "prometheus.yml",
    "prometheus.yaml",
    "alertmanager.yml",
    "alertmanager.yaml",
    "loki.yml",
    "loki.yaml",
    "promtail.yml",
    "promtail.yaml",
    "tempo.yml",
    "tempo.yaml",
    "otel-collector.yml",
    "otel-collector.yaml",
    "opentelemetry-collector.yml",
    "opentelemetry-collector.yaml",
    "jaeger.yml",
    "jaeger.yaml",
    "zipkin.yml",
    "zipkin.yaml",
}
OBSERVABILITY_PATH_MARKERS = {
    "prometheus",
    "grafana",
    "loki",
    "tempo",
    "otel",
    "opentelemetry",
    "jaeger",
    "zipkin",
    "logstash",
    "fluentd",
    "fluent-bit",
}
SERVICE_MESH_MARKERS = {
    "istio",
    "linkerd",
    "consul",
    "cilium",
    "envoy",
    "traefik",
    "nginx-ingress",
    "service-mesh",
    "servicemesh",
    "ingress",
    "gateway",
}
DATA_STORAGE_MARKERS = {
    "postgres",
    "mysql",
    "mariadb",
    "redis",
    "mongo",
    "mongodb",
    "cassandra",
    "clickhouse",
    "elasticsearch",
    "opensearch",
    "kafka",
    "minio",
    "s3",
}

TERRAFORM_EXTENSIONS = {".tf", ".tfvars"}

INFRA_DOMAINS = {
    "kubernetes",
    "helm",
    "terraform",
    "ansible",
    "docker",
    "ci",
    "observability",
    "service_mesh",
    "data_storage",
}

FIXED_INCLUDE_PATTERNS = {
    "*.tf",
    "*.tfvars",
    "Dockerfile*",
    "docker-compose*.yml",
    "docker-compose*.yaml",
    "compose.yml",
    "compose.yaml",
    "Jenkinsfile",
    ".gitlab-ci.yml",
    "azure-pipelines.yml",
    "requirements.txt",
    "pyproject.toml",
    "package.json",
    "package-lock.json",
}

DEFAULT_EXCLUDE_PATTERNS = {
    ".git/*",
    "**/.git/*",
    ".venv/*",
    ".venv/**",
    "**/.venv/*",
    "**/.venv/**",
    "venv/*",
    "venv/**",
    "**/venv/*",
    "**/venv/**",
    "**/node_modules/*",
    "**/dist/*",
    "**/build/*",
    "**/.idea/*",
    "**/.vscode/*",
    "**/__pycache__/*",
    "**/.pytest_cache/*",
    "**/.mypy_cache/*",
    "**/.ai_docs_cache/*",
    "**/.ai_docs_cache/**",
    ".ai_docs_cache/**",
    ".ai_docs_cache/*",
    "**/ai_docs_site/*",
    "**/ai_docs_site/**",
    "ai_docs_site/**",
    "ai_docs_site/*",
    ".ai-docs/*",
    ".ai-docs/**",
    "**/.ai-docs/*",
    "**/.ai-docs/**",
    "mkdocs.yml",
    "**/mkdocs.yml",
    "mkdocs_yml.md",
    "**/mkdocs_yml.md",
    ".ai-docs.yaml",
    "**/.ai-docs.yaml",
    "ai_docs/assets/*",
    "ai_docs/assets/**",
    "**/ai_docs/assets/*",
    "**/ai_docs/assets/**",
}

PRUNABLE_DIR_NAMES = {
    ".git",
    ".venv",
    "venv",
    "node_modules",
    "dist",
    "build",
    ".idea",
    ".vscode",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ai_docs_cache",
    "ai_docs_site",
    ".ai-docs",
}

PRUNABLE_DIR_PATHS = {
    "ai_docs/assets",
}
